theme: jekyll-theme-minimal
title: Orion-Kmer User Manual
description: A comprehensive guide to using Orion-Kmer, a blazing-fast k-mer toolkit.
baseurl: "/orion-kmer" # Assuming the repo name is orion-kmer
url: "https://motroy.github.io"
